dist: trusty
language: node_js
node_js:
- "12"

os:
- linux
addons:
  chrome: stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

jobs:
  include:
  - stage: lint
    script:
    - ng lint
  - stage: test
    script:
    - npm run test:lib-coverage
    - npm run report-coverage:lib
  - stage: build & publish showcase
    script:
    - npm run build:demo
    - npm run ls
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      local_dir: dist/ng-i18n-date-interval-showcase
      on:
        branch: master
    if: branch = master
  - stage: build & publish lib
    script:
    - npm run build:lib
    - npm run publish:lib
    if: branch = master